- android/app/src/main/java/com/hotwirerndemo/RNSession.kt
- android/app/src/main/java/com/hotwirerndemo/RNSessionManager.kt
- android/app/src/main/java/com/hotwirerndemo/RNSessionModule.kt
- android/app/src/main/java/com/hotwirerndemo/RNVisitableView.kt
- android/app/src/main/java/com/hotwirerndemo/RNVisitableViewManager.kt
- android/app/src/main/java/com/hotwirerndemo/ReactAppPackage.kt
- android/app/src/main/java/com/hotwirerndemo/Utils.kt
- demo/views/share.ejs
- ios/RNVisitableView.swift
- src/lib/Session.tsx
Fixes #14 
- android doesn't support async code response from WebView yet
> React Native <-> WebView communication support for Android 

- example/src/App.tsx
- example/src/config.ts
This PR addresses the comments left in review in #18.
> Remove unused constants and use single quotes

- packages/navigation/src/useWebviewNavigate.ts
This PR fixes an issue with pushing the wildcard screen to the stack. Previously we dispatched a navigation action with `type: "NAVIGATE`. The behavior of the navigator is to *not* push the same screen multiple times, even when the params have changed.
We should instead use the `PUSH` action from the StackNavigator.
This PR also fixes an issue where previously a Turbo action of type `replace` **would navigate back** instead of replacing the current screen with the new one.
> Support pushing wildcard screens; fix `replace` action

- .github/workflows/check.yml
Add simple GH actions to verify that pushed code has valid TS and is linting correctly
Example of broken builds (by pushing invalid code):
- https://github.com/software-mansion-labs/react-native-turbo-demo/actions/runs/7097860439
- https://github.com/software-mansion-labs/react-native-turbo-demo/actions/runs/7097826704
> Add Github Actions

- packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt
This PR addresses two minor bugs that were occurring within the Android application:
1. The refresh view was not being displayed after navigating back to the previous screen.
2. There were issues with page restoration.
App behavior before fix:
https://github.com/software-mansion-labs/react-native-turbo-demo/assets/44744462/48f8617a-bf54-4dfb-a7f9-fd8d467feef1
After fix:
https://github.com/software-mansion-labs/react-native-turbo-demo/assets/44744462/ddcd2a0c-b0c6-411b-966a-333b01d9c5f5
> Fix refresh and page restoration bugs on Android

- packages/turbo/android/src/main/java/com/reactnativeturbowebview/Utils.kt
As stated in the title, this PR adds support for converting JSONArray to Bundle in Utils.kt.
> Add support for converting JSONArray to Bundle in Utils.kt

- packages/turbo/README.md
- packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt
- packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt
- packages/turbo/ios/RNVisitableView.swift
- packages/turbo/ios/RNVisitableViewController.swift
- packages/turbo/ios/RNVisitableViewManager.m
- packages/turbo/src/RNVisitableView.ts
- packages/turbo/src/VisitableView.tsx
- packages/turbo/src/hooks/useActivityIndicator.tsx
- packages/turbo/src/hooks/useRenderLoading.tsx
This PR adds `renderLoading` prop which allows to define custom `ActivityIndicator` component.
> Support defining custom `ActivityIndicator` component

- example/src/MainScreen.tsx
- packages/navigation/src/hooks/useWebviewNavigate.ts
- packages/navigation/src/utils/isEqual.ts
This PR:
1. Fixes #100
2. Merges all important changes from #102 and #103 which are made by @pfeiffer and @WoLewicki. These changes include fixes for issues with nested navigators.
> Fix issues with nested navigators

- example/ios/TurboWebviewExample.xcodeproj/project.pbxproj
- example/src/App.tsx
- example/src/WebView.tsx
- example/src/navigationRef.ts
- packages/navigation/README.md
- packages/navigation/src/hooks/useWebviewNavigate.ts
This PR introduces a notable change in the `useWebviewNavigate` hook - from now we will return `linkTo` function as well as `getDispatchAction` function. We want to allow to define custom behaviour of `linkTo` function.
> Modal flow: introduce `getDispatchAction` function

- packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt
- packages/turbo/android/src/main/java/com/reactnativeturbowebview/Utils.kt
This PR rewrites the utility for parsing `JSONObject` to `WritableMap`. The previous version encountered issues when parsing `JSONArray`, as it could only correctly parse arrays with objects as items.
> Android: rewrite utility for parsing `JSONObject` to `WritableMap`

- packages/turbo/android/src/main/java/com/reactnativeturbowebview/Utils.kt
This PR modifies `convertJsonToMap` and `convertJsonToArray` functions to properly parse `null` values.
> Android: properly parse `null` values

- .release-it.js
Because `main` branch is protected, we need to push commits to other branch and make a PR. This should be done by some Github Action but for now I'm adding a simple hooks to release-it configuration.
`yarn release`
> Releases: push changes to separate branch

- .release-it.js
This PR overrides default tag name. 
`yarn release`
> Releases: change tag name

- packages/navigation/package.json
> Release react-native-web-screen@1.0.0-beta.2

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta

- packages/turbo/src/hooks/useStradaBridge.ts
This PR merges two `dispatchCommand` function calls into one. We don't need to call two commands separately. In the previous approach we might encounter problems with that approach - command might be dispatched to early causing Strada to not work properly.
1. Run example app
2. Test form page if submit button appears correctly
> StradaBridge: merge two `dispatchCommand` function calls into one

- packages/turbo/src/RNVisitableView.ts
This PR changes the approach for dispatching commands:
1. We don't have to set `setTimeout` for every command.
2. The order of execution is not guaranteed.
Using new `initializeWebView` function will reduce probability of race condition. 
1. `yarn clean && yarn && yarn ios`
2. Test if multiple commands are executed synchronously.
> RNVisitableView: do not wrap every command with `nextEventLoopTick`

- packages/navigation/package.json
> Release react-native-web-screen@1.0.0-beta.3

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.1

- packages/turbo/package.json
Bumps `turbo-ios` version to `7.1.0`
> Bump `turbo-ios` version

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.2

- .release-it.js
- package.json
- packages/navigation/package.json
- packages/turbo/package.json
- scripts/release.sh
- yarn.lock
This PR automates merging release PRs.
> Modify release process

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.3

- .github/workflows/check.yml
- package.json
- packages/turbo/android/build.gradle
- packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt
- packages/turbo/package.json
- packages/turbo/scripts/build-turbo-android.sh
- packages/turbo/scripts/postinstall.sh
- turbo.json
This PR:
1. Refactors `build.gradle` file
2. Modifies scripts for including local `turbo-android` library
`yarn clean && yarn && yarn dev:android`
> Android: modify scripts for including the local `turbo-android` library

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.4

- packages/turbo/package.json
This PR includes the `postinstall` script in the release files.
> Include the `postinstall` script in the release files

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.5

- package.json
- yarn.lock
This PR bumps `turbo` version.
> Bump `turbo` version

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.6

- packages/turbo/scripts/build-turbo-android.sh
- packages/turbo/scripts/build-turbo-ios.sh
This PR adds minor fixes to the build scripts.
`yarn clean && yarn && yarn dev:android`
`yarn dev:ios`
> Scripts: minor fixes

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.7

- packages/turbo/src/VisitableView.tsx
This PR changes the position of the `style` prop and enhances type.
> VisitableView: apply minor changes to `style` prop

- package.json
- yarn.lock
This PR bumps `turbo` package version.
> Bump `turbo` package version

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.8

- packages/turbo/README.md
This PR applies minor changes to `react-native-turbo` documentation.
> Update `react-native-turbo` documentation

- packages/turbo/package.json
> Release react-native-turbo@1.0.0-beta.9

- packages/navigation/package.json
> Release react-native-web-screen@1.0.0

- packages/turbo/package.json
> Release react-native-turbo@1.0.0

- packages/turbo/src/RNVisitableView.ts
This PR removes logical OR assignment operator which is problematic for `react-native` versions < 0.70
> RNVisitableView: remove logical OR assignment operator

- packages/turbo/package.json
> Release react-native-turbo@1.0.1

- packages/navigation/package.json
> Release react-native-web-screen@1.1.0

- packages/turbo/package.json
> Release react-native-turbo@1.1.0

- packages/turbo/package.json
> Release react-native-turbo@1.2.1
