software-mansion-labs/react-native-turbo

README.md, example/src/App.tsx, example/src/WebviewScreen.tsx, example/src/config.ts, src/useWebviewNavigate.ts
This PR adds support for defining the screen URLs relatively, following the React Navigation Linking conventions.
It also adds wildcard screen matching in the example app.
=> Add wildcard support and relative paths

packages/core/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt
Woah, this was a painful one.
I've tried to write the logic for running addView and removeView manually, and I've noticed that calling removeView sometimes works and sometimes doesn't change `isAttachedToWindow` which causes a fail when adding it to another container.
I think it's somehow related to RNscreens animations. Overall, the fix seems to work for me, but hope it works in your testing.
=> Fix crashes on going back on android

example/ios/Podfile, example/ios/Podfile.lock, packages/turbo/RNTurbo.podspec, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewController.swift, packages/turbo/ios/RNVisitableViewManager.swift, packages/turbo/ios/SessionSubscriber.swift
Releases the the `Turbo` package to the cocoapods repo under the name `RNTurboiOS` and adds it to the podspec.
Fixes: #32
=> Remove manual Turbo install

example/src/App.tsx, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSessionModule.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/src/Session.tsx, packages/turbo/src/SessionContext.ts, packages/turbo/src/VisitableView.tsx, packages/turbo/src/types.ts
This pull request adds support for cookies authorization and persistence in the Android application. The changes use android CookieManager to persist cookies between app runs.
Adds auth session example to the example app.
=> Adds support for cookie auth and an auth example

example/ios/Podfile.lock, example/package.json, yarn.lock
This PR bumps example app RN version. It resolves issues with new Xcode 15 and [build failure with target "React-Codegen"](https://stackoverflow.com/questions/75909819/react-native-m1-mac-build-failure-with-target-react-codegen)
Check if app is working properly by running the example app.
=> Bump React Native version to 0.70.13

example/server/views/share.ejs, example/src/App.tsx, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSessionModule.kt, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNSessionModule.swift, packages/turbo/src/common.ts
This PR:
1. Fixes an issue with `onMessage` not working on iOS. The main issue was that on Android, when a message is sent from the website, the event is being sent and caught with a `DeviceEventEmitter` listener. However, on iOS, the event was not being sent at all.
2. Replaces `DeviceEventEmitter` with `NativeEventEmitter `because it is deprecated.
3. Checks for the existence of the `AndroidInterface` variable. When the app was loading the example website on iOS, screen sharing would not work because `AndroidInterface` is not defined on iOS.
Run the app on iOS device and check if messages from the website are shown in the console.
=> Fix onMessage not working on iOS

packages/turbo/README.md, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewModule.kt, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNVisitableViewModule.m, packages/turbo/ios/RNVisitableViewModule.swift, packages/turbo/src/VisitableView.tsx, packages/turbo/src/types.ts
This PR is dependent on #53. Because of this reason, please review last three commits only!
This PR resolves #7: it adds support for custom user-agent in `Session` and `VisitableView` components.
Run the app where custom user-agent is being handled and check if there are any differences when using custom user-agent string.
=> Make user-agent of WebView customisable 

packages/navigation/src/useWebviewNavigate.ts
This PR fixes the problem in `useWebviewNavigate` hook -> urls with query string were not properly handled, causing `pathWithScreenParams` variable to have improper format.
=> Support urls with query string

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt
This PR fixes a bug with bottom tabs. On Android if you switch bottom tabs, `detachWebView` is not being called, causing the `WebView` not to unmount on the native side.
=> Fix not showing VisitableView when bottom tab has been changed on Android

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt
On Android native progressView/ActivityIndicator was not visible when opening slow loading page. It was caused by react-native behavior: to achieve performance, not all native components are being re-laid. Also manually re-laying the progressView in `onLayout` didin't work as expected. A fix from [here](https://github.com/facebook/react-native/issues/17968) solved this issue.
=> Fix native ActivityIndicator not being shown on Android

packages/turbo/android/src/main/AndroidManifest.xml, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNFileChooserDelegate.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNWebChromeClient.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNWebViewFileProvider.kt, packages/turbo/android/src/main/res/xml/file_provider_paths.xml
This PR adds support for file uploads in the WebView. Unfortunately, unlike with WKWebView on iOS, Android requires manual addition of the "upload modal" as it is not a built-in feature.
=> Handle file uploads on Android

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNWebChromeClient.kt
This PR depends on #51. Please review [feat: open target=_blank links in the external browser](https://github.com/software-mansion-labs/react-native-turbo-demo/commit/44f3de59c0cede6910d006bd9397a6bcd44f02bb) only!
This PR ensures external links open in an external browser. Previously, no action was taken when clicking on a link with `target=_blank`.
=> Open external links in an external browser

packages/navigation/src/useWebviewNavigate.ts, packages/turbo/src/VisitableView.tsx
Use navigation.replace action to replace screens. Also disable animation for that actions, so it will look seamless.
Before only `path` param was updated (so screen content was reloaded).
=> Use replace navigation action

packages/turbo/ios/RNSession.swift
When user press longer on any link in app, Safari shows link preview by default. Let's disable it in app for now (in future we might want enable it as feature depending on configuration?)
| Before | After |
|--------|--------|
| <img src=https://github.com/software-mansion-labs/react-native-turbo-demo/assets/6529801/72e191ed-a3da-4c33-b91d-9b3afe52eb70 width=300 /> | <img src=https://github.com/software-mansion-labs/react-native-turbo-demo/assets/6529801/1efc40e0-0d62-4dea-a7cf-0f045673a249 width=300 /> |
=> Disable link preview on iOS

packages/turbo/ios/RNSessionManager.swift
This PR sets a shared process pool on the `WKWebViewConfiguration`, which ensures that we share the same resources if multiple WKWebViews are in the app (ie. by multiple Sessions))
=> Implement shared process pool

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/ios/RNSession.swift
This PR enables debugging the WebView when app is in a `DEBUG` mode.
=> Enable WebView debugging

packages/turbo/src/hooks/useStradaBridge.ts
Previously `nativeBridge.register(..)` would be called multiple times - one for each component. This would make the the bridge adapter register after the _first_ component only, while subsequent component registrations didn't properly register on the web bridge.
The `NativeBridge#register` function takes an array of component names instead of a single one, so changing it to use this. This solves the issue we've seen with components not being picked up by the web bridge and pendingMessages being lost on the web side.
=> Strada: Fix registration of multiple components

packages/turbo/ios/RNVisitableView.swift
When app that uses `react-native-turbo` has many tabs, it often crashes. It is caused by calling `RNSession.unregisterVisitableView` when `visitableViews` list is empty.
@pklatka investigated it and found that `visitableWillAppear` is sometimes not called. So we can call it manually with this fix.
(related bugs: [one](https://stackoverflow.com/questions/131062/iphone-viewwillappear-not-firing) and [two](https://developer.apple.com/forums/thread/76834))
=> Fix app crash when using many tabs

packages/turbo/ios/RNVisitableView.swift
This PR modifies the approach used in #81. Directly invoking `viewWillAppear` on a view controller is not supported, and may lead to out-of-order callbacks and other inconsistent behaviors.
=> Do not call viewWillAppear directly on a view controller

example/ios/Podfile, example/ios/Podfile.lock, packages/turbo/README.md, packages/turbo/RNTurbo.podspec, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSessionManager.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/ReactAppPackage.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/SessionSubscriber.kt, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNSessionManager.m, packages/turbo/ios/RNSessionManager.swift, packages/turbo/ios/RNSessionSubscriber.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewController.swift, packages/turbo/ios/RNVisitableViewManager.m, packages/turbo/ios/RNVisitableViewManager.swift, packages/turbo/src/RNSessionManager.ts, packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx, packages/turbo/src/index.tsx, packages/turbo/src/types.ts
This PR:
1. Bumps `turbo-ios` version to `7.0.1` by publishing new fork to CocoaPods repository. Previous fork didn't have form submission callbacks implemented in `SessionDelegate`.
2. Exposes `didStartFormSubmission` and `didFinishFormSubmission` callbacks on `VisitableView`.
3. Adds `clearSnapshotCache` method to `VisitableView` which clears snapshots on a session which `VisitableView` operates.
=> Add form submission callbacks and snapshot clearing method

packages/turbo/README.md, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewManager.m, packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx
As stated in the title, this PR adds `pullToRefreshEnabled` prop which manages enabling 'pull-to-refresh' functionality.
=> Support disabling 'pull-to-refresh' functionality

example/ios/TurboWebviewExample.xcodeproj/project.pbxproj, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNSessionSubscriber.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewManager.m, packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx, packages/turbo/src/types.ts
This PR implements `sessionWebViewProcessDidTerminate` callback on iOS and `onRenderProcessGone` on Android and exposes `onContentProcessDidTerminate`, which, by default, reloads webView (similarly to [turbo-ios approach](https://github.com/hotwired/turbo-ios/blob/f4decce15e85218397638b241665604f739e2ba1/Source/Turbo%20Navigator/TurboNavigator.swift#L128-L130))
=> Support onContentProcessDidTerminate callback

packages/navigation/src/hooks/useWebviewNavigate.ts
Fixes #88
Use recursion to read `fullPath` from `payload` object. This solves issue when `fullPath` is not read on nested navigation.
=> Get correct key when payload has nested params

packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx
Thanks to @tjzel, this PR removes `@ts-expect-error` from RNVisitableView.
=> Remove @ts-expect-error in RNVisitableView

packages/turbo/src/VisitableView.tsx
This PR adds support for remounting Strada components as the URL is changed. This is important for screens that use `replace` where the params are updated (and via that the `url` prop), but the `VisitableView` stays the same.
=> VisitableView: Remount Strada component when URL changes

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt
This PR imports the `R` class from `turbo-android` to correctly identify native views provided by that library. While testing the library in Expo SDK 50 app, I discovered that Android fails to build because it searches for turbo constants in `react-native-turbo` instead of `turbo-android`.
=> Android: use assets from turbo-android

packages/turbo/src/hooks/useWebViewDialogs.ts
This PR removes `dispatch(true);` call which was causing to confirm the alert before `onPress` action.
=> Fix dispatching confirm action before alert onPress action

packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewController.swift
This PR refactors the iOS delegates and addresses a few issues:
1. Previously, we had an array of all registered visitableViews in the session, primarily to support modals in the same session. This is not recommended/supported by Turbo iOS, so we can drop support for this, which simplifies the code quite a lot.
2. We did not notify the `TurboSession` via `viewWillAppear` previously; Turbo contains a few optimizations to complete navigations while a forward/back animation is in-flight, so calling this now fixes that
3. The `RNVisitableViewController` inherits from `VisitableViewController` which already has delegates for `visitableViewWillAppear` and calling that on the TurboSession. We remove the explicit call here to avoid double-calling it.
=> iOS: Refactor and fix visitable delegates

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNWebChromeClient.kt
This PR is a follow-up of #107 - to maintain similarities on both platforms we get rid of `visitableViews` list and change it to one `visitableView`.
=> Android: store only one instance of the VisitableView

packages/navigation/src/hooks/useCurrentUrl.ts
This PR fixes a bug where `useCurrentUrl` returned a wrong result if used in tab navigator, where multiple screens would be mounted at the same time (ie. `lazy: false` or if swiping between two screens).
Previously the route params etc. were extracted in a very manual manner using `useNavigation()` and based on the `state.index`. Since multiple screens in the tab navigator would be mounted at the same time, while the `state.index` is static (until actually navigating), we returned the URL from one screen (the one corresponding to `state.index`) for all screens.
The solution is to use the built-in hook `useRoute()` to return the route for a screen.
=> Bugfix: Make `useCurrentUrl` work properly in top tab navigators

packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewController.swift
This PR fixes a "race condition" bug that happens when a visit is instantly proposed from a JavaScript visit (ie. the loaded page issues a `Turbo.visit(..)` on load.
In this case, the `visitableView` on the session would not be set before the new visit is proposed. This causes the proposal to be ignored, as there's no `visitableView` to notify.
Turbo iOS performs visit completion as part of the `..WillAppear(..)` flow, so this PR updates the place where we set the `visitableView` in `RNSession` to match that.
=> iOS: Fix visitProposal being proposed before a visitableView is set

packages/navigation/src/utils/unpackState.ts
This PR changes the behavior of a `unpackState` function - instead of unpacking the first route only we would like to respect the `state.index` value if present.
=> Follow focused route while unpacking state

packages/turbo/src/BridgeComponent.ts
This PR checks if name of the component is equal to the component name in Strada message. This way we make sure that the message is not broadcasted across all Strada components.
=> Do not broadcast Strada message across all Strada components

packages/navigation/src/hooks/useWebviewNavigate.ts, packages/navigation/src/utils/isEqual.ts
This PR adds a `areParamsSimilar` function to compare the params of 2 screens and see if they are to be considered “similar” enough to be removed. For this, we ignore path (which is always different, even if we should replace!) and params (which are also different).
=> Compare significant params only

packages/turbo/README.md, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSessionManager.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/SessionSubscriber.kt, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNSessionManager.m, packages/turbo/ios/RNSessionManager.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewManager.m, packages/turbo/ios/RNVisitableViewManager.swift, packages/turbo/src/RNSessionManager.ts, packages/turbo/src/VisitableView.tsx, packages/turbo/src/types.ts
This PR:
1. Introduces `getSessionHandles()` method which returns sessionHandles which are available on the native side
2. Introduces `reloadSession(sessionHandle)` method which reloads WebView for given sessionHandle
3. Introduces `refreshSession(sessionHandle)` method which issues a replace visit for given sessionHandle
4. Refactors `clearSnapshotCacheForAllSessions()` to `clearSessionSnapshotCache(sessionHandle)`
5. Properly issues a replace visit in `didProposeVisit` function on iOS
6. Introduces `refresh` method on `VisitableView` component
=> Refactor refresh/reload utilities

packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNVisitableView.swift
This PR removes code responsible for setting `visitableView` property in `RNSession` when `visitableDidDisappear` is called - this had to be done because this method is called also when we switch sessionHandles - maintaining nil `visitableView` makes impossible to call `refreshSession` on a session which is backgrounded.
=> RNSession: do not set visitableView to nil when `visitableDidDisappear` is called

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNWebChromeClient.kt
This PR fixes issues with opening the external browser and other actions which were handled by WebChromeClient.
=> Android: pass `RNSession` instance to `RNWebChromeClient`

packages/turbo/ios/RNVisitableView.swift
This PR makes sure, that controller reference is removed when VisitableView native component is removed from superview. Before that we were maintaining controllers for every visited url. Right now it will only store as many controllers as registered sessions.
=> iOS: deinitialize controller when native component unmounts

packages/turbo/src/VisitableView.tsx
In this PR, the `setTimeout` function wraps `onVisitProposal`. Sometimes `onVisitProposal` is invoked before `onFormSubmissionFinished`, and to prevent this behavior, we call `onVisitProposal` ### after a delay.
Using `setTimeout` instead of `requestAnimationFrame` provides a more generic solution. This is because `requestAnimationFrame` may behave differently on screens with higher refresh rates.
=> Call `onVisitProposal` with a delay

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt
This PR removes `detachWebView` call in `RNSession`. From now, `onDropViewInstance` in `RNVisitableViewManager` is  responsible for detaching WebView. This method properly calls `detachWebView` when needed (for example it's not called when changing bottom tabs).
=> Android: do not detach WebView in RNSession

packages/navigation/src/hooks/useWebviewNavigate.ts
This PR fixes how `getMinimalAction` is determined when doing `replace` visits.
Provided that:
```
* RootStack
* AuthenticatedStack
* SomeModal
```
```
* RootStack
* AuthenticatedStack
* SomeOtherScreen
```
Previously, the minimal action would be:
```
// Replace:
* AuthenticatedStack
* SomeOtherScreen
```
.. which would have the effect that `SomeModal` would still be open after dispatching the replace.
After this PR, the minimal action is:
```
// Replace:
* SomeOtherScreen
```
.. which will close the `SomeModal` screen and replace it with `SomeOtherScreen` as expected.
=> Support `replace` actionType when determining the minimal action

packages/turbo/ios/RNSessionSubscriber.swift, packages/turbo/ios/RNVisitableView.swift
This PR makes the `controller` property optional in `RNVisitableView` on iOS. The reason for this change is to handle a case where we call `refreshSession` on a session that has no mounted native component. Currently, because we set controller property to `nil`, this results in an app crash.
=> iOS: Make `controller` property optional in `RNVisitableView`

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt
This PR changes first passed argument to the `TurboWebView` constructor - this change is needed to support `<select>` tags.
=> Android: pass `activity` to `TurboWebView` instead of `reactContext`

packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx, packages/turbo/src/utils/nextEventLoopTick.ts
This PR 
1. Wraps `dispatchViewManagerCommand` function with `setTimeout`. This way we avoid calling the native method before the native `sessionHandle` prop is set up. 
2. Introduces `nextEventLoopTick` function whose purpose is to map the behavior of [process.nextTick](https://nodejs.org/docs/latest/api/process.html#processnexttickcallback-args) function.
=> Avoid calling the native method before the native `sessionHandle` prop is set up

packages/turbo/android/src/main/java/com/reactnativeturbowebview/Utils.kt
This PR modifies `convertJsonToMap` and `convertJsonToArray` functions to properly parse `null` values.
Clone of #145
=> Android: properly parse `null` values

examples/turbo-demo-expo-example/package.json, yarn.lock
This PR makes sure that we use local `react-native-turbo` and `react-native-web-screen` packages. 
=> Example app: use local packages

packages/turbo/RNTurbo.podspec
This PR updates RNTurbo.podspec to use local files only.
=> iOS: update `RNTurbo.podspec`

packages/navigation/src/buildWebScreen.tsx
This PR fixes a bug where the `fullPath` param was always set on the first route in the unpacked state. The first route might not always be the active one, so this PR changes it to use the states `index` to determine the active route in the `routes`.
=> Fix issue with routes in `getStateForPath`

packages/turbo/README.md
This PR adds information to the docs about the different behavior of the title parameter in the `onLoad` callback.
=> Docs: mention about different behavior when the title of a webpage is empty

packages/turbo/ios/RNSession.swift
`WKWebView` by default calculates the safe area for displaying the page content. This sometimes results in the content being cropped. Setting `contentInsetAdjustmentBehavior` to `.never` will override this default behavior.
Made sure that everything is displayed correctly.
=> iOS: make sure that `WKWebView` has correct size

packages/turbo/ios/RNSessionManager.m, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewManager.m
This PR fixes warnings which occur during compilation.
`yarn clean && yarn && cd examples/turbo-native-expo-example && yarn ios`
=> iOS: fix compilation warnings

packages/turbo/src/VisitableView.tsx
This PR modifies the component ordering within `VisitableView.tsx` to ensure that the `Error` and `Loading` components are displayed in front of `RNVisitableView`. This change addresses an issue observed during navigation away from a screen that has encountered an error. Previously, the error view was momentarily hidden during the back navigation transition (this was especially visible on Android). With this adjustment, the error view maintains its visibility throughout the entire transition.
Made sure that `Error` component is being shown when navigating back.
=> VisitableView: change component rendering order

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/ios/RNVisitableView.swift
This PR changes the logic of `refresh` method - we no longer dispatch `replace` visit, instead, the JS script is injected which calls `refresh()` method on `Turbo.session` object. 
Added a `setTimeout` in `WebView.tsx` and checked if website is refreshed properly.
=> Change logic of `refresh` method

packages/turbo/src/RNVisitableView.ts
This PR refactors the `initializeWebView` function to ensure that `webViewRef` is properly initialized and changes the `dispatchCommand` function body to always use early returns. This addresses some edge cases where `webViewRef` could potentially be uninitialized.
`yarn && yarn dev:ios`
=> Ensure that `webViewRef` is initialized in `initializeWebView` function

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt
This PR adds a check in `onDropViewInstance` which ensures that `detachWebView` is called when the app context is available. A similar check is done in `ViewManager.onDropViewInstance` when recycling the view.
=> Android: ensure that `WebView` is detached when application context is available

packages/turbo/src/VisitableView.tsx
Somehow this was completely missed, currently `VisitableView` doesn't expose `style` prop. This PR exposes this prop to enable applying custom styles to `RNVisitableView`.
=> VisitableView: expose `style` property

packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewController.swift
This PR makes sure that all completion handlers have been called before webView navigates to other url. There is a possibility that `sendAlertResult` or `sendConfirmResult` are going to be called too late which can result in `NSInternalInconsistencyException`.
=> iOS: ensure that all completion handlers have been called

packages/turbo/README.md, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt, packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx, packages/turbo/src/types.ts
This PR adds a `progressViewOffset` property which allows to override default offset values for `webViewRefresh` in `turbo-android`.
`yarn clean && yarn && yarn dev:android`
=> RNVisitableView: introduce `progressViewOffset` property

packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNSession.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableView.kt, packages/turbo/android/src/main/java/com/reactnativeturbowebview/RNVisitableViewManager.kt, packages/turbo/ios/RNSession.swift, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewManager.m, packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx
This PR: 
1. Introduces `webViewDebuggingEnabled` property on `VisitableView` to enable the remote debugging using Safari / Chrome. Now remote debugging is disabled by default, but can be enabled by setting the property to `true`. 
2. Changes the place of calling the `visit()` function in `RNVisitableView.swift`. Now the `visit()` function is called in `didSetProps` to make sure that all props are being initialized. Without that change, somehow url `didSet` is called before `sessionHandle` which causes the WKWebView not to mount.
Tested on iOS and Android using the example app.
=> VisitableView: introduce `webViewDebuggingEnabled` property

packages/turbo/src/hooks/useStradaBridge.ts, packages/turbo/src/utils/stradaBridgeScript.ts
This PR changes the way of passing the message object to `window.webBridge` in `sendToBridge` function - previous approach was causing a crash when someone passed a string with  unescaped `'` character - now the object is passed without wrapping it with a string.
=> Strada: change the way of passing the message object to `window.webBridge` 

packages/turbo/README.md, packages/turbo/ios/RNVisitableView.swift, packages/turbo/ios/RNVisitableViewManager.m, packages/turbo/patches/turbo-ios.patch, packages/turbo/src/RNVisitableView.ts, packages/turbo/src/VisitableView.tsx
This PR introduces a `refreshControlTopAnchor` property which allow to set the topAnchor of the native refresh control on iOS. Removing the constraint completely can introduce some unexpected behaviors, especially when using transparent header, so with this prop we can manually set the desired top offset of the native refresh control when needed.
=> iOS: introduce `refreshControlTopAnchor` property

packages/turbo/ios/RNVisitableView.swift, packages/turbo/src/BridgeComponent.ts, packages/turbo/src/hooks/useMessageQueue.ts, packages/turbo/src/types.ts
This PR provides a comprehensive fix for issues with Strada Bridge Components that occur after Turbo Frame navigations or redirects. It ensures that components remain active and that native iOS state remains synchronized, correcting functionality like pull-to-refresh.
This PR addresses two problems - #228 and iOS Pull-to-Refresh regression. To fix the iOS regression, this PR introduces an approach similar to what was mentioned in #227 - it has been resolved by adding a Key-Value Observer to the WKWebView's url property in RNVisitableView.swift. This restores pull-to-refresh and ensures native state consistency. 
We can test both Bridge components and pull-to-refresh functionalities work as expected by using the specific branch of the demo server.
This …
=> Fix: BridgeComponents and sync iOS URL after frame navigations
